---
# installs an arbitrary homebrew cask package

- name: tap a repo
  homebrew_tap: tap={{ tap }} state=present
  when: tap is defined

- name: install {{ item }}
  homebrew_cask: name={{ item }} state=present
  with_items: packages
  when: packages is defined

- name: install {{ package_name }}
  homebrew_cask: name={{ package_name }} state=present
  when: package_name is defined
